name: 🐛 Bug Report
description: Report a bug or issue with the Sports Prediction System
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Which environment is affected?
      placeholder: "e.g., production, staging, local development"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or screenshots to help explain your problem.
      placeholder: Paste error logs here...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down, data loss)
        - High (Major functionality broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Sports Data Ingestion
        - Game Prediction Engine
        - API Endpoints
        - Database (Cosmos DB)
        - Authentication
        - Infrastructure (Terraform)
        - CI/CD Pipeline
        - Testing Framework
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser/Client
      description: If applicable, which browser or client are you using?
      placeholder: "e.g., Chrome 91, Postman, curl"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I have tested this in the latest version
          required: false
