name: ✨ Feature Request
description: Suggest a new feature for the Sports Prediction System
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem this feature addresses...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Describe alternatives you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking our usage)
        - High (Would significantly improve our workflow)
        - Medium (Nice to have)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Sports Data Ingestion
        - Game Prediction Engine
        - API Endpoints
        - Database (Cosmos DB)
        - Authentication
        - Infrastructure (Terraform)
        - CI/CD Pipeline
        - Testing Framework
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature.
      placeholder: |
        1. As a [user type], I want [goal] so that [benefit]
        2. When [situation], I need [functionality] to [outcome]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: input
    id: implementation-complexity
    attributes:
      label: Implementation Complexity (Optional)
      description: If you have technical knowledge, estimate the complexity
      placeholder: "e.g., Simple API change, Complex ML model integration, Infrastructure changes"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided clear acceptance criteria
          required: true
        - label: I have considered the impact on existing functionality
          required: false
