name: staging
url: https://sports-prediction-staging.azurewebsites.net
reviewers:
  - "devops-team"
protection_rules:
  required_reviewers: 1
  wait_timer: 5  # 5 minutes
  prevent_self_review: true
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true
variables:
  AZURE_RESOURCE_GROUP: "rg-sports-prediction-staging"
  AZURE_LOCATION: "East US"
  ENVIRONMENT_NAME: "staging"
secrets:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_STAGING }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_STAGING }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE_STAGING: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_STAGING }}
  FUNCTION_APP_URL_STAGING: ${{ secrets.FUNCTION_APP_URL_STAGING }}
